---
- hosts: leafs
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown2
    - rdnbr
    - quagga
- hosts: spines
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown2
    - quagga
- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown
#    - ifplugd
- hosts: server04
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - apache
